# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparse_to_full <- function(pmat) {
    .Call('_comparator_sparse_to_full', PACKAGE = 'comparator', pmat)
}

elementwisecpp <- function(x, y, attrs) {
    .Call('_comparator_elementwise', PACKAGE = 'comparator', x, y, attrs)
}

pairwisecpp <- function(x, y_, attrs, full) {
    .Call('_comparator_pairwise', PACKAGE = 'comparator', x, y_, attrs, full)
}

