# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparse_to_full <- function(pmat) {
    .Call('_comparator_sparse_to_full', PACKAGE = 'comparator', pmat)
}

elementwisecpp <- function(x, y, m_S4) {
    .Call('_comparator_elementwise', PACKAGE = 'comparator', x, y, m_S4)
}

pairwisecpp <- function(x, y_, m_S4, full) {
    .Call('_comparator_pairwise', PACKAGE = 'comparator', x, y_, m_S4, full)
}

